name: Supabase Keep Alive
on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday
  workflow_dispatch: # This enables the "Run" button

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Curl Ping
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/posts?limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
